### ISSUE TITLE
Appropriate exit status when tests are failing

### ISSUE THREAD

**Issue by mpahuja** [allure-framework/allure-mocha#14]
I am trying to use the reporter from jenkins, is there a way to have the mocha-allure-reporter pass the correct exit status based on whether all the tests passed or failed?

This is more of a question rather than an issue, i would expect something like 

process.exit(failures) in the runner.on(end,function()) call back. 
Do I need to set some configuration for this to work?

Also please note that trying to use mocha-multi with spec or progress along with mocha-allure-reporter did not help either.

**Comment by just-boris** [comment]
There was issue in mocha-multi when it returns wrong exit code: https://github.com/glenjamin/mocha-multi/pull/12
now it is fixed, be sure that you have latest version installed

**Comment by mpahuja** [comment]
yeah i am using "mocha-multi": "^0.9.0"

**Comment by mpahuja** [comment]
@just-boris Any idea why this may be happening?

**Comment by just-boris** [comment]
I cannot reproduce it.
We have a repository with example setup: https://github.com/allure-examples/mocha-allure-example and it runs tests using the following command `multi='progress=- mocha-allure-reporter=-' mocha`. Mocha takes care about test results and returns proper exit code, regarding from test results

**Comment by DeChrish** [comment]
No updates?

**Comment by just-boris** [comment]
@DeChrish there are no updates because in my project it works fine.

@DeChrish If you have the same issue, please provide me an example where you are getting wrong status code and then maybe I can help you.

**Comment by DeChrish** [comment]
@just-boris 
https://github.com/allure-framework/mocha-allure-reporter/issues/17
