### ISSUE TITLE
Jenkins Job - mocha-allure failure

### ISSUE THREAD

**Issue by DeChrish** [allure-framework/allure-mocha#17]
If the mocha test fails, the allure report is generated with failed status, but the Jenkins build is Sucess

**Comment by just-boris** [comment]
This is probably the same as #14 

@DeChrish have you tried to update adapter to latest version and check out our demo setup?

**Comment by DeChrish** [comment]
Thanks,
 i am using grunt for mocha reporter, i could not find the setup for grunt. 

var config = {
        mochaTest: {}
    };
    config.mochaTest[name] = {
        options: {
            reporter: 'mocha-allure-reporter',
            reporterOptions: {
                targetDir: allureReportFolderName
            },
            timeout: 60000,
            logErrors: true,
            captureFile: directories.target + '/' + name + '/test-results.txt'
        },
        src: grunt.option("mochatestspecs").split(",")
    };
