### ISSUE TITLE
Issue when using promise with 'createStep'

### ISSUE THREAD

**Issue by Jayasankar-m** [allure-framework/allure-mocha#24]
@just-boris 
Hi,
This is more of a question (might not be an issue with the reporter)

I'm using protractor with mocha and allure-report

I was trying to create a function that can validate both strings and promises.
Also the checkpoint result should come as substep in the report.

I created a class "CheckPoint" as follows
```js
var CheckPoint = function () {
    this.Expect = function (checkpointname, actual, expected) {
		var x = this
		var retprm = new Promise(function (resolve, reject) {
			var substep = allure.createStep("Expected: " + expected + "   Actual: {0}", function (act) {
				if (act !== expected) {
					throw new Error("Expected: " + expected + "   Actual: " + act)
				}
			})
			Promise.resolve(actual).then(function (val) {
				allure.createStep(checkpointname, function () {
					substep(val)
				})()
			})
		})
		return retprm
	}
}
module.exports = CheckPoint;
```

and test as follows 
```js
var cp = require('../lib/CheckPoint.1.js')
var cpo = new cp();
describe('Test Suite',function(){
    it('Test',function(){
		var prom = new Promise(function(resolve,reject){
            resolve(true)
        })
                cpo.Expect("Test1",prom,false)
		cpo.Expect("Test2",true,false)
		cpo.Expect("Test3",true,true)
    })
})
```

**in the result,the step result show failure warning symbol but the overall testresult is pass (which is not the expected behavior).
I need the test also to fail in this case as there are failed cases
Screenshot is attached**

Is this an issue with the reporter ?
Any way i can achieve the above case ?

Thanks!!!!
![promise_issue](https://cloud.githubusercontent.com/assets/18571086/22682756/97c2c642-ed3a-11e6-86c8-12690e578a2d.png)

**Comment by just-boris** [comment]
It is not a problem of Allure. The thing is that you didn't tell Mocha, that your testcase is failed. So Allure did not receive that information as well.

You need to return a promise from the test function, so Mocha can wait until your promise will be resolved and will check the result. Also, you have 3 calls in your test, I believe that they also should be called after each other

```
it('test', () => {
  return cpo.Expect('Test1', prom, false)
    .then(() => cpo.Expect('Test2', true, false))
    .then(() => cpo.Expect('Test3', true, true))
})
```

**Comment by Jayasankar-m** [comment]
@just-boris 
Thank you for the reply!!!!
I tried to adapt the same ,but getting the same result.
I'm attaching the files.
Am i missing something??
As mentioned before,the purpose is to have a single function 'CheckPoint' that can be used to validate strings and promises ,the result of which need to be logged in the report.
[AllureTest.zip](https://github.com/allure-framework/allure-mocha/files/758045/AllureTest.zip)

**Comment by Jayasankar-m** [comment]
@just-boris 
Was able to achieve it using 'expect' from 'chai' and the code format mentioned in the post..
Attaching the files..

```
var chai = require('chai');
var expect = chai.expect;

var CheckPoint = function () {
    this.Expect = function (checkpointname, actual, expected) {
        var substep = allure.createStep("Expected: " + expected + "   Actual: {0}", function (act) {
            if (act !== expected) {
                expect(act).to.equal(expected)
            }
        })
        return Promise.resolve(actual).then(function (val) {
            allure.createStep(checkpointname, function () {
                substep(val)
            })()
        })
    }
}
module.exports = CheckPoint;

```
closing the issue!!

Thanks again for the reply!!
[AllureTest.zip](https://github.com/allure-framework/allure-mocha/files/767221/AllureTest.zip)

**Comment by sumeetp4** [comment]
Hey @Jayasankar-m , Need your help for the same thing
I am trying to have allure.createStep in another js file where I need to send parameters.
And I want to call that function in my test js file?
But allure.createStep does not execute
Can I share my code with you?

**Comment by Jayasankar-m** [comment]
Sure..send the code...

**Comment by sumeetp4** [comment]
[AllureDemo.zip](https://github.com/allure-framework/allure-mocha/files/1743154/AllureDemo.zip)

Here I am testing an android application using Appium with webdriverio and mocha
And I am using allure reporter.

LaunchApplication.js is my test file which calls function in applicationUtilites.js which in turn calls function in mobileActions.js

I have used createStep in mobileActions.js but that part is not being executed.

Config folder contains all the configuration required for appium and all the required modules used.

Let me know if you find the issue.

**Comment by Jayasankar-m** [comment]
Hi Sumeet,

  Can you try returning a call to the 'maintap' as below in the
'mobileActions.js' file.

var performTap = function (message, driver, element) {
    console.log("Inside perform Tap");
    var mainTap = allure.createStep(message, function () {
        console.log("inside createStep");
        return driver
            .waitForExist(element, 20000)
            .touchAction(element, 'tap');
    });
    *return mainTap();*
}



Regards
Jayasankar

**Comment by sumeetp4** [comment]
Thanks @Jayasankar-m , it worked liked a charm
Also do you know how to clear earlier xml that are generated in allure-results folder, so that I have the latest run xml only

**Comment by Jayasankar-m** [comment]
Hi Sumeet,
I'm not aware of any allure specific commands for this.
But, you can do that with the package.json with 'preLaunchDisney'

**Comment by sumeetp4** [comment]
Hey @Jayasankar-m 
Okay I will try that. Have you used allure.createAttachment and tried attaching a screenshot for a failed scenario?

**Comment by kat0072** [comment]
@sumeetp4 : Try using "**allure generate --clean .**" will clean the existing allure-report folder and generate the new resources so you don't have to do it manually. --clean is the parameter which you can use in the code.
