### ISSUE TITLE
allure report generation fails when this.skip() is used in the test case

### ISSUE THREAD

**Issue by sunilaadike** [allure-framework/allure-mocha#25]
When this.skip() is used in the test case, mocha-allure-reporter generates the xml file with stop="" status="", so with this block in the xml file allure report generation fails with error

![image](https://cloud.githubusercontent.com/assets/25978374/24000841/69772692-0a82-11e7-8f56-50d99923d6ac.png)

**Comment by sunilaadike** [comment]
xml which got generated with mocha-allure-reporter

**abc.xml**

<test-case start="1489673533681" stop="" status="">
			<name> command on VM : undefined</name>
			<title> command on VM : undefined</title>
			<labels>
			</labels>
			<parameters>
			</parameters>
			<steps>
			</steps>
			<attachments>
			</attachments>
		</test-case>

**Comment by just-boris** [comment]
Fixed and released as `1.3.1`
