### ISSUE TITLE
Cannot read property 'currentTest' of undefined

### ISSUE THREAD

**Issue by netmajor** [allure-framework/allure-mocha#26]
Hi,
I have add to my mocha test:
```
describe('Open browser and search someting in google  ', () => {
 allure.feature('Open browser');  
  allure.story('search someting in google');
});
```
but when feature function is executed, it fails in allure-js-commons because suites is empty.
```

Allure.prototype.getCurrentSuite = function() {
    return this.suites[0];
};
```

How can I add suite by your api ? I dont see that option :/

**Comment by just-boris** [comment]
Wrap your feature definition in `beforeEach`

```js
describe('Open browser and search someting in google  ', () => {
  beforeEach(() => {
    allure.feature('Open browser');  
    allure.story('search someting in google');
  });

  it('your test', () => {
    // ...
  })
});
```

**Comment by netmajor** [comment]
Unfortunately it doesn't work. Still same error 'Cannot read property 'currentTest' of undefined'

**Comment by netmajor** [comment]
Hi, i have attached my simple test project. Please check it and maybe you could tell my why  allure not work. I am trying to have in folder 'ike' main feature for all tests in subdirectories.
But i get 'TypeError: Cannot read property 'currentTest' of undefined' when I execute allure.Story in tests in subdirectory :/

[mocha-allure-example.zip](https://github.com/allure-framework/allure-mocha/files/948259/mocha-allure-example.zip)

**Comment by netmajor** [comment]
I still have problem with add feature and story. Allure2 and mocha 3.4.1 allure-comanline 2.0
My code looks like in your example :

```
describe('Open browser and search someting in google  ', () => {
  beforeEach(() => {
    allure.feature('Open browser');  
    allure.story('search someting in google');
  });

  it('your test', () => {
    // ...
  })
});
```

And I get error:

Cannot read property 'currentTest' of undefined
running chrome
TypeError: Cannot read property 'currentTest' of undefined
    at Allure.getCurrentTest (...\node_modules\allure-js-commons\index.js:25:34)
    at Allure.addLabel (...\node_modules\allure-js-commons\runtime.js:53:18)
    at Allure.feature (...\node_modules\allure-js-commons\runtime.js:81:10)
    at Context.beforeEach 


Please help

**Comment by netmajor** [comment]
I add simple project with this error. I am using webdriverio, mocha and allure2. Please help :)
[Web.zip](https://github.com/allure-framework/allure-mocha/files/1010307/Web.zip)

**Comment by just-boris** [comment]
Hello! I looked at your code and have figured out, that you are using two allure instances at the same time: [mocha-allure-reporter](https://github.com/allure-framework/allure-mocha), but also the [wdio-allure-reporter](https://github.com/webdriverio/wdio-allure-reporter).

These two frameworks are mutually exclusive, you can't use them both. Actually, when you are using `wdio` as a test runner, passing reporter to `mochaOpts` is not supported, you should use `wdio-allure-reporter` only.

However, that reporter does not provide some of Allure features, like steps or stories. See the issue https://github.com/webdriverio/wdio-allure-reporter/issues/37 for details. 

If you want to use such features, you need to go with this project (mocha-allure-reporter). It supports all features but requires more effort to setup. You will have to deal with launching browsers and concurrent test runs manually, but we believe that as soon as you have so complex test setup, that requires more Allure features, you will be also able to make a bit more complex steps to set up, but get the full benefits of Allure.

**Comment by netmajor** [comment]
Hi, tnx for find time for check my code!
Easiest for me is to use https://github.com/webdriverio/wdio-allure-reporter because I have too much test wrote using it. I hope that you manage to write extra api to this reporter ;) do you know when you find time for this?

**Comment by netmajor** [comment]
Currently I have tests that runs concurrently ;) so I am ready to use features, stories and steps :)
