### ISSUE TITLE
Global allure object is undefined for beforeAll hook

### ISSUE THREAD

**Issue by szarlatan** [allure-framework/allure-mocha#28]
Hello,

I found out that the global allure object is undefined for the beforeAll hook, what made me sad. Is there a reason for that?

I am testing the API endpoints, but as I want test to be as fast as possible I create a single request, save the response and then fire number of assertions against it.

```
describe('GET /health', function() {
     let response;

     before('response code is 200', function() {
         return deviceregistry
             .get('/health')
             .set('Accept', 'application/json')
             .expect(200)
             .then(function(res) {
                 response = res;
             })
             .catch(function(error) {
                  throw new AssertionError(error);
             });
     });

     it('responds with JSON object', function() {
        assert.isObject(response.body, 'Response body in not a JSON object');
     });

     and so on...
});
```

The problem I find about is that I would like to log more info in case of failure of this beforeAll, so in this `.catch()` block e.g. create attachment with the stacktrace, or so...

On the other hand allure object works fine for `beforeEach`. What's the difference about those two hooks?

Regards,
Kris.

**Comment by just-boris** [comment]
Hello!

Acually in our [example with Mocha](https://github.com/allure-examples/mocha-allure-example/blob/master/test/simple.spec.js#L6) we are calling `allure.createStep` in `before` hook.

However, most extra options of Allure report are avaiable only during test running. This is due Allure nature, where all information is attached to a single test, so you can't add any more information without having test case running.

A solution for you probably would be to add one testcase before others that logs all information and does some preliminary assertions that you want to have.
