### ISSUE TITLE
Pass options in command line

### ISSUE THREAD

**Issue by psprogis** [allure-framework/allure-mocha#32]
Is there a way to change targetDir using command line arguments or create some config file ?

**Comment by just-boris** [comment]
try 
```
mocha --reporter mocha-allure-reporter --reporter-options targetDir=./your/path
```
Did it work?

**Comment by psprogis** [comment]
Yes, thank you! It works. Main problem was to use multiple reporters.

[mocha-multi-repoters](https://www.npmjs.com/package/mocha-multi-reporters) allows to use config file with options for more that 1 reporter, e.g.:
`{
  "reporterEnabled": "spec,mocha-allure-reporter",

  "mochaAllureReporterReporterOptions": {
    "targetDir": "./output/allure-results"
  }
}`

**Comment by just-boris** [comment]
Can't give a strong advice here.
[In our examples](https://github.com/allure-examples/mocha-allure-example) we are using another library - [mocha-multi](https://github.com/glenjamin/mocha-multi)
