### ISSUE TITLE
Unable to use spec and allure-mocha-reporter together

### ISSUE THREAD

**Issue by shashi-raja** [allure-framework/allure-mocha#34]
I have started using allure-mocha-reporter by passing below line in my mocha.opts
`--reporter allure-mocha-reporter`

But after this I am not getting console output of the tests.
I want to have both console output with spec reporter and separate report with allure reporter.
How can I do this?

**Comment by just-boris** [comment]
Look at our example: https://github.com/allure-examples/mocha-allure-example
It uses [mocha-multi](https://github.com/glenjamin/mocha-multi) to use multiple reporters.
