### ISSUE TITLE
Allure report display 404 not found

### ISSUE THREAD

**Issue by fedika** [allure-framework/allure-mocha#35]
Dear allure-mocha,
First of all thank you provide allure-mocha.
So I already have xml file generated by command `node_modules/mocha/bin/mocha --reporter mocha-allure-reporter` (located in allure-results folder)

```
<?xml version='1.0'?>
<ns2:test-suite xmlns:ns2='urn:model.allure.qatools.yandex.ru' start='1511950006135' stop='1511950007154'>
    <name>Customer</name>
    <title>Customer</title>
    <test-cases>
        <test-case start='1511950006135' status='passed' stop='1511950006717'>
            <name>check mandatory fields</name>
            <title>check mandatory fields</title>
            <labels/>
            <parameters/>
            <steps/>
            <attachments/>
        </test-case>
        <test-case start='1511950006718' status='passed' stop='1511950007154'>
            <name>should get customer data</name>
            <title>should get customer data</title>
            <labels/>
            <parameters/>
            <steps/>
            <attachments/>
        </test-case>
    </test-cases>
</ns2:test-suite>
```

Then I run this command `node_modules/allure-commandline/bin/allure generate allure-results --clean` to generate html file, then it display `Report successfully generated to allure-report` and allure-reports created and contains html file and other files.

But when I open the html file. It display 404 not found.

Thank you, I'm very appreciate your help :)

**Comment by just-boris** [comment]
@baev could you please look what's up with this XML file?
