### ISSUE TITLE
How do I get HTML report with this?

### ISSUE THREAD

**Issue by sumeetp4** [allure-framework/allure-mocha#37]
Hi,

I have created a test file. I am using 
"mocha Demo.js --reporter mocha-allure-reporter" to run my Demo.js file
I see allure-results folder is been created and there are reports in form of xml files
How do I get reports in form of HTML?

**Comment by just-boris** [comment]
Use `allure` commad-line tool. You can add this as a part of your test workflow, for example how it is defined here:
https://github.com/allure-examples/mocha-allure-example/blob/master/package.json#L15

**Comment by sumeetp4** [comment]
So it takes the xml file and converts it into HTML report? How do I directly generate the HTML file while running my test?

**Comment by just-boris** [comment]
`allure-mocha` as a package itself doesn't give you that possibility. You always have to run another process to convert test results.

You can ask folks in our [Gitter room](https://gitter.im/allure-framework/allure-core), maybe they have some examples.

**Comment by sumeetp4** [comment]
Thanks @just-boris 
One more thing, so this line
"report": "allure generate allure-results --clean -o allure-report && allure open allure-report"
converts the xml files into HTML report on opens it on some server.
How do I save it in my local machine and take a look at it later rather than opening it in browser after test is complete. What are the different options?

**Comment by sumeetp4** [comment]
Also, when I'm trying to take Screenshot using client, it is giving me error
client.takeScreenshot is not a function

**Here is my code:**
var config = require('./helpers/desiredCapabilities').options;
var client = webdriverio.remote(config);

Using this same from the example, instead of browser, I have client which is my webdriverio object

 afterEach("take screenshot on failure", function() {
        if (this.currentTest.state !== "passed") {
        	client.takeScreenshot().then(function (png) {
                allure.createAttachment('Screenshot', function () {
                    return new Buffer(png, 'base64')
                }, 'image/png')();
            });
        }	
      });

**Comment by sumeetp4** [comment]
Okay so I now I changed client.takeScreenshot() to client.saveScreenshot(), but I'm not able to attach to my allure here
I have tried like this
var screenshot = client.saveScreenshot("./demo.png");
allure.createAttachment('Screenshot',  new Buffer(screenshot.value,'base64'), 'image/png')

**Comment by sumeetp4** [comment]
I'm getting the png file saved but it throws error

The first argument must be one of type string, Buffer, ArrayBuffer, Array, or Array-like Object. Received type object
                <stack-trace>TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be one of type string, Buffer, ArrayBuffer, Array, or Array-like Object. Received type object

**Comment by ManikandanRajendran** [comment]
> Thanks @just-boris
> One more thing, so this line
> "report": "allure generate allure-results --clean -o allure-report && allure open allure-report"
> converts the xml files into HTML report on opens it on some server.
> How do I save it in my local machine and take a look at it later rather than opening it in browser after test is complete. What are the different options?

It is just creating xml report for me and not the HTML report even after using the above command in package.json :(

**Comment by just-boris** [comment]
Check our `allure generate` command
