### ISSUE TITLE
How to get steps in test body under test cases in HTML report

### ISSUE THREAD

**Issue by sumeetp4** [allure-framework/allure-mocha#38]
How do I get test body in my test case results.
I am testing android mobile application and using Appium, mocha and webdriverio
![untitled](https://user-images.githubusercontent.com/29970107/36368460-5854db28-157d-11e8-9a6d-91af145a6a06.png)

**Comment by just-boris** [comment]
See our example: https://github.com/allure-examples/mocha-allure-example/blob/master/test/simple.spec.js#L14

There are some sample steps defined

**Comment by sumeetp4** [comment]
Can I get step results for each click, tap, setValue?

**Comment by just-boris** [comment]
You will need to wrap them yourself. Allure-mocha doesn't know about any automation tool that you are using.

**Comment by sumeetp4** [comment]
Okay, I so need to do this  
const clickOkayButton= allure.createStep("Clicking okay", () => {
    // do something
   return browser.click();
  });

for each step?

**Comment by sumeetp4** [comment]
Also why am I getting this when createStep and call that function in my it

[mochawesome] Error: Invalid log report arguments.

[mochawesome] Error: Invalid log report arguments.
allure-js-commons: Unexpected endStep(). There are no any steps running

**Comment by sumeetp4** [comment]
Also how do I attach a screenshot for a failed scenario?
I am using webdriverio standalone and mocha

**Comment by sumeetp4** [comment]
Hey @just-boris I'm new to this, if you could help me

**Comment by just-boris** [comment]
> Also how do I attach a screenshot for a failed scenario?
Check the example package more carefully. There are covered most common cases and a lot of comments
https://github.com/allure-examples/mocha-allure-example/blob/master/test/webdriver-io.spec.js#L103

> Also why am I getting this when createStep and call that function in my it [mochawesome] Error: Invalid log report arguments.

Mochawesome is totally different project. Can't help you with that

**Comment by sumeetp4** [comment]
Okay my bad..earlier I was trying with mocha awesome.
Can you tell me how do I clear earlier generated xml files, so that everytime I run my tests, only latest xml file is there in the allure-results folder.

**Comment by DeepTom** [comment]
> Okay my bad..earlier I was trying with mocha awesome.
> Can you tell me how do I clear earlier generated xml files, so that everytime I run my tests, only latest xml file is there in the allure-results folder.

To do that, you can do the following :
1. Clean the folder in which your allure reports are being generated by your wdio run.
2. If your allure server is already running then run the command to generate allure report : 
allure generate [allure_output_dir] --clean. After running the command hit refresh on browser in which your allure server is opened already.
3. If your allure server is not running then run the command to generate allure report :
allure generate D:/Development/Automation/WebdriverIO/project/WDOIOBasic/allure-results && allure open
Use the following if it gives you an error saying that it is already in use or something.
allure generate D:/Development/Automation/WebdriverIO/project/WDOIOBasic/allure-results --clean && allure open

**Comment by govind413** [comment]
@just-boris , Same issue I have with nightwatch, can you please tell me how to integrate above steps in nightwatch allure report?
