### ISSUE TITLE
Custom logo plugin does not seem to work

### ISSUE THREAD

**Issue by sumeetp4** [allure-framework/allure-mocha#41]
So I followed the steps that are mentioned here 

https://docs.qameta.io/allure/#_step_8_enabling_a_plugin

Under .\node_modules\allure-commandline\dist\config

Updated allure.yml with
plugins:
  - junit-xml-plugin
  - xunit-xml-plugin
  - trx-plugin
  - behaviors-plugin
  - packages-plugin
  - screen-diff-plugin
  - xctest-plugin
  - custom-logo-plugin

and ran the genrerate report allure-command line

So under ./allure-report/plugins folder, I see  custom-logo folder is created, but in the report the logo is not changed.

**Comment by BorisOsipov** [comment]
@sumeetp4 It isn't related to `allure-mocha`. It is an allure2 issue and it was reported here https://github.com/allure-framework/allure2/issues/659
