### ISSUE TITLE
Allure severity example

### ISSUE THREAD

**Issue by saritanzu** [allure-framework/allure-mocha#42]
I've been trying to add Allure severity to my project but failed. It does not recognize it. 
I tried adding it to each it block, with not luck. Can you please provide an example of how can you declare the severity?

```
   it('Should test allure severity', function () {
allure.severity(blocker);        
browser.url('./' + login_url);
//also tried this:
allure.SEVERITY.BLOKER
    });
```
Thanks!

*Using wdio and mocha

**Comment by just-boris** [comment]
This should work.

Seems like you are using different allure plugin: https://github.com/webdriverio/wdio-allure-reporter.
That plugin indeed does not support this: https://github.com/webdriverio/wdio-allure-reporter/issues/37

**Comment by saritanzu** [comment]
Oh, I see, thanks alot!

**Comment by shreyasjoshi9** [comment]
I found this way. you have to use it as a notation above a method.
Please check the correct format. I am stuck somewhere else but I know how to use this one.
import allure
@allure.severity(allure.severity_levels.BLOCKER)
def blahblah():
...
You can only use BLOCKER, CRITICAL, NORMAL, MINOR or TRIVIAL as severity values. If you put anything else, by default it takes "normal".
