### ISSUE TITLE
add a custom logo/text with hyperlink to Jira in the logs

### ISSUE THREAD

**Issue by Sourabhmochagit** [allure-framework/allure-mocha#50]
Hello,

I want to add a way through which, if a test fails, in the report, user should get a option in the form of hyperlinked text/logo to JIRA and if user clicks on it, he will be directed to JIRA with pre populated values from the log.

Please let me know if this is possible.

**Comment by just-boris** [comment]
* adding links to the issues is described here: https://github.com/allure-framework/allure-js-commons/issues/13
* info about logo customization can be found here: https://github.com/allure-framework/allure2/issues/659
