### ISSUE TITLE
using allure-mocha reporter with cypress - package-json-cullify script err

### ISSUE THREAD

**Issue by fraser-m-hurley-LTK** [allure-framework/allure-mocha#52]
Hi, I'd like to use allure with my cypress project. Cypress supports mocha reporters so I thought I'd give allure-mocha a go. Allure works so long as I don't try and use the runtime API. When I add `require("mocha-allure-reporter");` to a file I get an error:
`Error: Cannot find module './scripts/package-json-cullify' from 'C:\Users\fraser\code\node_modules\mocha'`.

Is anyone able to help in debugging whats going on?

**Comment by xuxinya** [comment]
I got the same trouble.
have got any helps ??

**Comment by just-boris** [comment]
Hello!

I have investigated the issue. Cypress tries to browserify the reporter code. Our reporter code was never supposed to work in browser and therefore fails un the unexpected environment.

I do not think there will be any sooner solution, unless Cypress changes something in their architecture.

cc @bahmutov

**Comment by Shelex** [comment]
For those interested into integrating allure with cypress, there is [cypress-allure-plugin](https://github.com/Shelex/cypress-allure-plugin).
