### ISSUE TITLE
take snapshoot on each createstep

### ISSUE THREAD

**Issue by carlosflima** [allure-framework/allure-mocha#54]
Hi,

It's possible using an function/argument/etc with createstep to capture screenshoot?

I need to show more then 1 print by It/Test, like step by step.

Thanks

**Comment by vitali-storchous** [comment]
@carlosflima 
as an example, you could do it like this:
let yourStepFunction = allure.createStep('step name...', async function() {
  await allure.createAttachment('screenshot', Buffer.from(await driver.takeScreenshot(), 'base64'))
  // your step implementation...
})

**Comment by EINBOX** [comment]
@vitali-storchous can you put more in order to use on.

**Comment by vitali-storchous** [comment]
@EINBOX 
`
function createStep(stepName, func) {
    let snapshot
    // here you make a snapshot and save it into snapshot varialbe
    allure.createAttachment(stepName, snapshot)
    return allure.createStep(stepName, func)
}

let actionOne = createStep('do something', () => {
    // ...
})

let actionTwo = createStep('do something more', () => {
    // ...
})

actionOne()
actionTwo()
`
