### ISSUE TITLE
mocha-allure-reporter with Cypress get trouble

### ISSUE THREAD

**Issue by xierxy** [allure-framework/allure-mocha#55]
Trying to use mocha-allure-reporter for Cypress(Mocha) E2E-tests and with , but got a trouble.

code in /plugins/index.js

```
require('mocha-allure-reporter')

module.exports = (on, config) => {
  on('task', {
    'setAllureSeverity': () => {
      console.log(allure._allure)
      allure.severity(allure.SEVERITY.BLOCKER)
      return null
    } 
  })
}
```

code in test.js

```
it('solution #1: 线框按钮-color', function() {
      cy
        .task('setAllureSeverity')
        .get('.button.button--normal.button--default').eq(0)
        .should(($button) => {
           ...
        })
    })
```

console.log is empty：Allure { suites: [], options: { targetDir: 'allure-results' } }

My versions:

node v8.9.3（cypress/.node-version）
mocha v5.2.0
mocha-allure-reporter v1.4.0
Cypress package version: 3.3.2
Cypress binary version: 3.3.2

Thank you in advance!

**Comment by jhernandezinzunzaTechtonic** [comment]
I enjoy using Allure, but wish it was actually compatible with Cypress as well.

**Comment by Shelex** [comment]
@xierxy @jhernandezinzunzaTechtonic 
Please check [cypress-allure-plugin](https://www.npmjs.com/package/@shelex/cypress-allure-plugin)

**Comment by just-boris** [comment]
Nice solution, thanks for sharing, @Shelex!
