### ISSUE TITLE
How to fail step manually?

### ISSUE THREAD

**Issue by inikolaeva** [allure-framework/allure-mocha#61]
I have some tricky checks and therefore I want to fail the step in report manually. Could you please clarify how to do it?

**Comment by just-boris** [comment]
Steps marked as failed if any assertion inside is failed. If you have a complex check, it should end with an assertion anyways:

```js
import { strict as assert } from 'assert'
import {allure} from 'allure-mocha/runtime'

it('test', () => {
    allure.step('Complex check', () => {
         const result = doComplexCheck();
         assert.ok(result);
    })
})
```
