### ISSUE TITLE
allure.createAttachement is not a function

### ISSUE THREAD

**Issue by Ahmar828** [allure-framework/allure-mocha#66]
using mocha-allure-reporter 1.4.0 with puppeteer

I am trying to attach screen shot with allure report. Report is generating correctly but allure.createattachment() function is not working.

I wrote this function in afterEach when test fails:

```
const screenshot = await page.screenshot("screenshot"); 
allure.createAttachement('screenShot', screenshot, 'image/jpg')
```

I am getting error message:

TypeError: allure.createAttachement is not a function
at Context.afterEach (genral/base.js:66:20)
at process._tickCallback (internal/process/next_tick.js:68:7)

Please Help!

**Comment by just-boris** [comment]
the function is called: `createAttachment` and not `createAttachement`, no middle "e"

**Comment by ohlori** [comment]
I encounter this too.
I have this
`afterEach(async function() {
    const png = await browser.takeScreenshot();
    allure.createAttachment("Screenshot", new Buffer(png, "base64"), "image/png");
});`
![image](https://user-images.githubusercontent.com/48617573/117371501-f8a73580-ae95-11eb-97ee-0c8384cfc381.png)

**Comment by ohlori** [comment]
This worked for me 
`require("mocha-allure-reporter");`
`declare const allure: any;`

**Comment by VladMaxPower** [comment]
> `createAttachment` and not `createAttachement`, no middle "e"
this is from the npm documentation, I think it's worth removing the extra "e"
<img width="689" alt="Снимок экрана 2021-12-13 в 17 56 17" src="https://user-images.githubusercontent.com/42372727/145844994-15b077a7-3d1a-46d1-8d87-4ad0762f588c.png">
