### ISSUE TITLE
failed step is marked `passed`

### ISSUE THREAD

**Issue by igor-rubis** [allure-framework/allure-mocha#70]
Hello
I've just started working with `allure-mocha` so it might be I misconfigured it. But I'm facing the following issue:
I use `allure-mocha` with nightwatchjs and it has built-in assertions. When something fails, it marks test  as `broken` which is  also not good since it's an assertion error (should be `failed`), but a failed step in a report is passed despite the error message is attached to it.
The code:
```
allure.createStep(`Verify menu items order by title: ${itemsList}`, () => {
  this.api.elements('css selector', `${mainContainer} > a`, (result) => {
    this.assert.strictEqual(result.value.length, itemsList.length);
  });
}
```
The report:
![image](https://user-images.githubusercontent.com/6901769/129477851-5b4d47c3-6441-429a-95aa-395618ba3c9e.png)

I tried to use chai assertions directly
```
const { assert } = require('chai');

//all the other code

assert.strictEqual(result.value.length, itemsList.length);
```
IN this case it marks the test `failed` which is correct, but still the failed step ha status `passed`

**Comment by just-boris** [comment]
This is expected, according to the logic in [the source code](https://github.com/allure-framework/allure-mocha/blob/master/index.js#L61).

Nightwatch uses a custom error which does not match [the expected convention](https://github.com/nightwatchjs/nightwatch/blob/main/lib/assertion/assertion-error.js#L7).

As for the attempt using chai, I think (without looking at the actual code) that Nightwatch has some special logic in propagating only their own errors.

The best option would be to stick to the nightwatch's built-in matchers and deal with broken as the only status

**Comment by igor-rubis** [comment]
Thank you for the information
