### ISSUE TITLE
Is there a way to add TestCaseID for AllureTestOps?

### ISSUE THREAD

**Issue by zookzooki** [allure-framework/allure-mocha#71]
Hi, i am looking to add Testcase id in my mocha tests (using js). I did:
```
 it(title, async () => {
        allure.addLabel('testId', '5564);
        // checking test
      });
 ```
where 5564 - is test id in allure TestOps
But I see 6597 - test id and 5564 link after running the test . And I can see error message ('Test case was deleted') after clicking on #6597

![111](https://user-images.githubusercontent.com/49098080/134674185-4bf6baca-c051-4804-af55-180cd1d25595.png)

I know on python I can use 
```
@allure.id("1234")
def some_test():
    some_code()
```
And it will be work (the 'Links' won't appear in this case)

What am I doing wrong maybe?

P.S. Also I can't use https://github.com/allure-framework/allure-js/tree/master/packages/allure-decorators

,Thx for helping

**Comment by baev** [comment]
You can use 'ALLURE_ID' label for that
